### ISSUE TITLE
Show movies

### ISSUE THREAD

**Issue by CoderKiwi** [CoderKiwi/Volo#3]
# Description
Show a list of movies using tiles (like in Netflix or the Apple TV app) on the home page.

# Outcomes
1. The movies should be shown as horizontal lists of tiles
1. Each horizontal list should have a title describing the list (most anticipated, trending, etc.)
1. The top ten of each category is shown
1. The background of the tile should be an appropriate image of the movie
1. The title of the movie should be shown
1. The year of the movie should be shown

# Tasks
- [x] Find suitable library for styling - bootstrap-vue
- [x] Find way to obtain images - [this article by Trakt](https://apiblog.trakt.tv/how-to-find-the-best-images-516045bcc3b6)
- [x] Add basic nav bar showing movies page heading
- [x] Add base media component 'tile'
- [x] Show those lists of movies in a horizontal array of tiles - [this article helped](https://www.freecodecamp.org/news/horizontal-scrolling-using-flexbox-f9d16817f742/), to [disable horizontal scrolling](https://stackoverflow.com/questions/3296644/hiding-the-scroll-bar-on-an-html-page)
- [x] Add calls to get Trakt trending, anticipated, popular, etc. movies
- [x] Add calls to get images of media, add to tiles
- [x] Add 'About' page which notes the use of Trakt, Fanart
