### ISSUE TITLE
Plex integration

### ISSUE THREAD

**Issue by CoderKiwi** [CoderKiwi/Volo#6]
# Description
The admin needs the ability to communicate with their (one) Plex server. 

# Outcomes
1. Plex settings can be entered (hostname, port, etc.) in a Settings page so that the app is authorized to communicate with the Plex server
1. The admin does not need to enter a token themselves, rather the app should obtain a token for them. Generally, the setup process should be as painless as Plex's APIs allow
1. These settings persist between Docker containers
1. The name of the Plex server is shown in a Settings page

# Tasks
- [ ] Add a server Node.js app
- [ ] Add logging solution
- [ ] Document the API - [Swagger](https://swagger.io/solutions/getting-started-with-oas/)
- [ ] Investigate using a PIN to link accounts - see [this doc](https://github.com/Arcanemagus/plex-api/wiki/Plex.tv#urls) and [this](https://github.com/plexinc/node-plex-api#pin-authenticate-by-pin-code)
- [ ] Investigate sqlite framework for persistent storage - [bet
